saloni-15/Heel2Toe

index.html
styles.css

Added parallax scrolling effect to background images of the _best-seller_ and _latest-trend_ section
Also added text-shadow to the headings of the respective sections mentioned above.
- [✔ ] I have performed a self-review of my own code.
- [✔ ] I'm a contributor in Hacktoberfest'21.

Added Parallax Scroll effect

---

index.html
script.js
styles.css

Added a "back-to-top" button.
🔧 Fixes #2
<hr/>

 Added a "back-to-top" button.

---

README.md

Update Project readme

---

index.html

🔧 Fixes #(19)
Fixed footer Women's section link
<hr/>

Fixed footer Women's section link

---

.github/ISSUE_TEMPLATE/create_issue.yaml
.github/issue_template.md

updated the form-issue template

---

index.html
styles.css

replaced Helvetica with Inter and Bebas Neue wherever necessary.
🔧 Fixes #9
<hr/>

changed page fonts for a better experience

---

styles.css

I have added the smooth scroll behavior and changed the look of the scroll bar.
🔧 Fixes #6 
<hr/>  
This is the updated scroll bar.
<hr/>

added scroll behaviour and changed the appearance.

---

contact.html
index.html
styles.css

I have created a contact.html which contains a styled HTML form. I have also updated the anchor tags corresponding to **Contact** in NavBar as well as on the Footer, They now redirect to the newly created contact.html.
🔧 Fixes #(30)
<hr/>  
<hr/>

Created Contact.html and updated all the link

---

index.html

Best sellers page added

---

contact.html
styles.css
trending.html

Created the trending page. 
<hr/>  
<hr/>

Added modifications to the trending page

---

contact.html
styles.css

Improved the styling of contact form and added the heading.
🔧 Fixes #34 
<hr/>  
<hr/>

adding contact page

---

contact.html
styles.css

- Removed second contact form
- Changed the background color of body
🔧 Fixes #58 
<hr/>  
<hr/>

fixed contact form

---

womem.css
women.html

#31 Add NavBar to women.html
Added a navigation bar consistent with the home page. 
Removed the women option so the user does not get confused. 
Added little hover effects which to seem fancy but not too fancy
I believe the hover effect can be applied overall to the whole site as well. (A Suggestion)
#31
<hr/>  
<hr/>

Added navigation bar to women.html

---

styles.css

- Fixed visibility of Trending page header.
🔧 Fixes #61  
<hr/>  
<hr/>

fixed Trending page header

---

index.html
styles.css
trending.html

For fixing conflicts, I made new branch and make this new pull request. These are things I fixed/made :
1. Create anchor styles for column1 class (cause address class have been removed)
2. Add missed links (trending and best sellers) in footer
3. Sync footer of main page and trending page
#59 
<hr/>  
**HOME** 
**TRENDING**
<hr/>

add footer's anchor style and update footer links

---

index.html
styles.css
trending.html

Someone fixed Footer background but I made some changes have a look.
🔧 Fixes #65 
<hr/>  
<hr/>

Fixed footer

---

bestSeller.html

I added the bestSeller.html page and modified it using carousel.
<hr/>  
<hr/>

modified bestseller.html page

---

index.html

linked it to navbar and explore more.
<hr/>  
<hr/>

Added arrivals.html page

---

.vscode/settings.json
css/styles.css
index.html

i updated the responsiveness of the footer section in which i reduced font size which was recommended by you. If need any changes do let me know
🔧 Fixes #74 74
<hr/>  
<hr/>

responsivefooter + updated

---

arrivals.html
css/arrivals.css

Issue #84 - Added navbar to new arrivals page.
<hr/>  
<hr/>

Added navbar to new arrivals page

---

best.html
css/best.css

Issue #82: Updated the styling of the text of the carousel on the best seller page. The changes are made in best.html and best.css.
<hr/>  
<hr/>

style: improve-carousel-text

---

css/styles.css
index.html

I aligned Heel2Toe to Quick Links in order to increase aesthetics. I also changed the Quick Links font size in order to increase readability and understanding.
Unaligned elements in footer and "quick links" looks like a link #80 
<hr/>  
<hr/>

Aligned Footer and changed QUICK LINKS size

---

contact.html
css/contact.css

Added Navigation Bar In Contact.html And added responsiveness in it 
🔧 Fixes #85 
<hr/>  
<hr/>  
- [✔ ] I have performed a self-review of my own code.
- [ ✔] I'm a contributor in Hacktoberfest'21.
<hr/>
Please tell me If I can do more
Thank You !!

Add navbar on Contact page

---

README.md

Have added badges for issues open ,issue closed, pull requests open etc.
🔧 Fixes #94
<hr/>  
<hr/>

added badges in Readme

---

best.html
css/best.css

just changed color of the title of best seller page and add some margin in last section's button.

did changes in bestseller page

---

arrivals.html
css/arrivals.css
css/men.css
css/women.css
men.html
women.html

Update responsive navbar on women. html, men.html, and arrivals.html for consistency
🔧 Fixes #104 
<hr/>  
On women.html
On men.html
On arrivals.html
<hr/>

Update responsive navbar

---

css/product.css
product.html

🔧 Fixes #88
Redesigned the Single Product VIew Page 
<hr/>  
<hr/>

Redesigned the Single Product VIew Page || Added

---

css/styles.css

Reverts saloni-15/Heel2Toe#109

Revert "Corrected the overlapping in the Navbar and aligned the content for b…"

---

arrivals.html
css/arrivals.css
css/men.css
css/women.css
men.html
women.html

Reverts saloni-15/Heel2Toe#105

Revert "Update responsive navbar"

---

css/best.css

🔧 Fixes #(82)
Fixed crousel styling on best sellers page
<hr/>  
<hr/>  
- [ x ] I have performed a self-review of my own code.
- [ x ] I'm a contributor in Hacktoberfest'21.

request-82 Carousel design fixed

---

best.html
css/best.css
trending.html

The Trending page navbar brand name now returns to the homepage
The bestseller page navbar is now similar to the men's and women's navbar without affecting the carousel.

Bestseller and trending pages navbar

---

arrivals.html
best.html
contact.html
css/allbtns.css
css/best.css
css/men.css
css/styles.css
css/women.css
index.html
men.html
product.html
trending.html
women.html

I have added animation to all the buttons which were not having any earlier.
🔧 Fixes #114
<hr/>  
https://user-images.githubusercontent.com/71200145/136149410-9cc56432-8bde-44ba-bd47-1e564df315eb.mov
<hr/>

Add animations to all the buttons

---

css/men.css
css/women.css
men.html
women.html

resolved overlapping issue in men and women section

---

css/kids.css
css/men.css
css/women.css

Fix Explore Now button to be responsive in all screen sizes. Results as seen below.
🔧 Fixes #206 
<hr/>  
<hr/>

fix explore now button to be responsive on tablet
